spring:
  application:
    name: spring-oauth2-server
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:oauth2
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  sesion:
    store-type: REDIS
    redis:
      flush-mode: IMMEDIATE
      namespace: oauth2:server:session
  security:
    filter:
      order: 3
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
server:
  servlet:
    session:
      timeout: 180s
  port: 8099
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
