spring:
  application:
    name: spring-oauth2-resource-server
  profiles:
    active: dev
  thymeleaf:
    cache: false
  security:
    filter:
      order: 3
oauth:
  server:
    url: http://www.oauth2-server.com:8099
  client:
    id: resourceClientId
    secret: secret
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
server:
  port: 8098
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
